### ISSUE TITLE
List supported sites

### ISSUE THREAD

**Issue by FoxxMD** [rroller/media-roller#2]
What sites does this support? Or link to which libraries are backing the download mechanism so we can find a list of supported sites.

**Comment by rroller** [comment]
The backing library is youtube-dl. I'll update the README with this info.
* http://ytdl-org.github.io/youtube-dl/
* https://github.com/ytdl-org/youtube-dl

For the list of sites see http://ytdl-org.github.io/youtube-dl/supportedsites.html or see the extractors at https://github.com/ytdl-org/youtube-dl/tree/master/youtube_dl/extractor
