### ISSUE TITLE
Shortcut fix

### ISSUE THREAD

**Issue by alexcroox** [rroller/media-roller#8]
The shortcut didn’t work when choosing from a share sheet. This was the fix:

![674FB61F-9F01-47C0-B044-7784283AF504](https://user-images.githubusercontent.com/1065835/141200594-3591db24-7a97-453e-a5c6-6b4c3a21da3b.jpeg)

**Comment by rroller** [comment]
Thanks, i'll try to update this.

**Comment by Two-Play** [comment]
Fixed version: https://www.icloud.com/shortcuts/d3b05b78eb434496ab28dd91e1c79615

**Comment by rroller** [comment]
Thanks will check it out

**Comment by rroller** [comment]
Worked! Will update the readme
